---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opp-policy-ansible
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: opp-policy-ansible
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: {{ include "opp.ansibleConfigMapArgoSyncOptions" . | quote }}
    opp-policy/ansible-checksum: {{ include "opp.ansibleConfigChecksum" . | quote }}
data:
{{ include "opp.regionaldrAnsibleConfigMapData" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opp-policy-ansible
  namespace: {{ include "opp.clusterCaMgtNamespace" . }}
  labels:
    app.kubernetes.io/name: opp-policy-ansible
    app.kubernetes.io/component: ca-workloads
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
data:
{{ include "opp.regionaldrAnsibleConfigMapData" . }}
