apiVersion: v1
kind: ConfigMap
metadata:
  name: odf-ssl-extractor-playbooks
  namespace: openshift-config
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
data:
  odf-ssl-certificate-extraction.yml: |
{{ .Files.Get "scripts/ansible/odf-ssl-certificate-extraction.yml" | indent 4 }}
  tasks_kubeconfig.yml: |
{{ .Files.Get "scripts/ansible/tasks/kubeconfig.yml" | indent 4 }}
  tasks_kubeconfig_attempt.yml: |
{{ .Files.Get "scripts/ansible/tasks/kubeconfig-attempt.yml" | indent 4 }}
  tasks_odf_ssl_extract_ca.yml: |
{{ .Files.Get "scripts/ansible/tasks/odf-ssl-extract-ca.yml" | indent 4 }}
  tasks_odf_ssl_delete_pods.yml: |
{{ .Files.Get "scripts/ansible/tasks/odf-ssl-delete-pods.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odf-ssl-precheck-playbooks
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
data:
  odf-ssl-precheck.yml: |
{{ .Files.Get "scripts/ansible/odf-ssl-precheck.yml" | indent 4 }}
  tasks_kubeconfig.yml: |
{{ .Files.Get "scripts/ansible/tasks/kubeconfig.yml" | indent 4 }}
  tasks_kubeconfig_attempt.yml: |
{{ .Files.Get "scripts/ansible/tasks/kubeconfig-attempt.yml" | indent 4 }}
