{{- if .Values.argocdHealthMonitor.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-health-monitor
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: argocd-health-monitor
    app.kubernetes.io/component: cronjob
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 20
      activeDeadlineSeconds: 6000
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: argocd-health-monitor
            image: quay.io/validatedpatterns/utility-container:latest
            workingDir: /playbooks
            env:
            - name: PRIMARY_CLUSTER
              value: {{ include "opp.primaryClusterName" . | quote }}
            - name: SECONDARY_CLUSTER
              value: {{ include "opp.secondaryClusterName" . | quote }}
            - name: FORCE_SYNC_APP_NAMESPACE
              value: {{ .Values.argocdHealthMonitor.forceSyncAppNamespace | default "openshift-gitops" | quote }}
            - name: FORCE_SYNC_APP_NAME
              value: {{ .Values.argocdHealthMonitor.forceSyncAppName | default "ramendr-starter-kit-resilient" | quote }}
            - name: FORCE_SYNC_RESOURCES
              value: {{ include "opp.forceSyncResourcesJson" . | quote }}
            - name: FORCE_SYNC_RESOURCE_KIND
              value: {{ .Values.argocdHealthMonitor.forceSyncResourceKind | default "Namespace" | quote }}
            - name: FORCE_SYNC_RESOURCE_NAME
              value: {{ .Values.argocdHealthMonitor.forceSyncResourceName | default "ramendr-starter-kit-resilient" | quote }}
            command:
            - ansible-playbook
            args:
            - -i
            - localhost,
            - -c
            - local
            - /playbooks/argocd-health-monitor-cron.yml
            volumeMounts:
            - name: playbooks
              mountPath: /playbooks
              readOnly: true
          volumes:
          - name: playbooks
            configMap:
              name: argocd-health-monitor-playbooks
              items:
              - key: argocd-health-monitor-job.yml
                path: argocd-health-monitor-job.yml
              - key: argocd-health-monitor-cron.yml
                path: argocd-health-monitor-cron.yml
              - key: tasks_kubeconfig.yml
                path: tasks/kubeconfig.yml
              - key: tasks_get_managed_clusters.yml
                path: tasks/get_managed_clusters.yml
              - key: tasks_argocd_health_check_one_attempt.yml
                path: tasks/argocd-health-check-one-attempt.yml
          serviceAccountName: argocd-health-monitor
{{- end }}
