apiVersion: batch/v1
kind: Job
metadata:
  name: odf-ssl-certificate-extractor
  namespace: openshift-config
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
    app.kubernetes.io/component: certificate-extraction
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      containers:
      - name: odf-ssl-extractor
        image: quay.io/validatedpatterns/utility-container:latest
        workingDir: /playbooks
        resources:
          requests:
            memory: "768Mi"
            cpu: "200m"
          limits:
            memory: "1536Mi"
            cpu: "1000m"
        env:
        - name: PRIMARY_CLUSTER
          value: {{ include "opp.primaryClusterName" . | quote }}
        - name: SECONDARY_CLUSTER
          value: {{ include "opp.secondaryClusterName" . | quote }}
        - name: ANSIBLE_NOCOLOR
          value: "true"
        command:
        - ansible-playbook
        args:
        - -i
        - localhost,
        - -c
        - local
        - -v
        - /playbooks/odf-ssl-certificate-extraction.yml
        volumeMounts:
        - name: playbooks
          mountPath: /playbooks
          readOnly: true
      volumes:
      - name: playbooks
        configMap:
          name: odf-ssl-extractor-playbooks
          items:
          - key: odf-ssl-certificate-extraction.yml
            path: odf-ssl-certificate-extraction.yml
          - key: tasks_kubeconfig.yml
            path: tasks/kubeconfig.yml
          - key: tasks_kubeconfig_attempt.yml
            path: tasks/kubeconfig-attempt.yml
          - key: tasks_odf_ssl_extract_ca.yml
            path: tasks/odf-ssl-extract-ca.yml
          - key: tasks_odf_ssl_delete_pods.yml
            path: tasks/odf-ssl-delete-pods.yml
      restartPolicy: Never
      serviceAccountName: odf-ssl-extractor-sa
  backoffLimit: 10
  activeDeadlineSeconds: 3600
