{{- if eq "1" (include "opp.s3SslEnabled" . | trim) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: s3-ssl-certificate-sync
  namespace: {{ include "opp.clusterCaMgtNamespace" . }}
  labels:
    app.kubernetes.io/name: s3-ssl-certificate-management
    app.kubernetes.io/component: certificate-extraction
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      containers:
      - name: s3-ssl-sync
        image: {{ $.Values.ansible.containerImage }}
        workingDir: /playbooks
        resources:
          requests:
            memory: "768Mi"
            cpu: "200m"
          limits:
            memory: "1536Mi"
            cpu: "1000m"
        env:
        - name: PRIMARY_CLUSTER
          value: {{ include "opp.primaryClusterName" . | quote }}
        - name: SECONDARY_CLUSTER
          value: {{ include "opp.secondaryClusterName" . | quote }}
        - name: ANSIBLE_NOCOLOR
          value: "true"
        - name: CLUSTER_READINESS_MAX_ATTEMPTS
          value: {{ ((.Values.s3Ssl | default dict).clusterReadinessMaxAttempts | default 150) | quote }}
        - name: CLUSTER_READINESS_SLEEP_SECONDS
          value: {{ ((.Values.s3Ssl | default dict).clusterReadinessSleepSeconds | default 30) | quote }}
        - name: CLUSTER_CA_MGT_NAMESPACE
          value: {{ include "opp.clusterCaMgtNamespace" . | quote }}
        - name: CA_BUNDLE_NAME
          value: {{ include "opp.s3SslCaBundleName" . | quote }}
        - name: CA_BUNDLE_NAMESPACE
          value: {{ include "opp.s3SslCaBundleNamespace" . | quote }}
        - name: CA_BUNDLE_KEY
          value: {{ include "opp.s3SslCaBundleKey" . | quote }}
        command:
        - ansible-playbook
        args:
        - -i
        - localhost,
        - -c
        - local
        - -v
        - /playbooks/s3-ssl-certificate-sync.yml
        volumeMounts:
        - name: playbooks
          mountPath: /playbooks
          readOnly: true
      volumes:
      - name: playbooks
        configMap:
          name: s3-ssl-sync-playbooks
          items:
          - key: s3-ssl-certificate-sync.yml
            path: s3-ssl-certificate-sync.yml
          - key: tasks_kubeconfig.yml
            path: tasks/kubeconfig.yml
          - key: tasks_kubeconfig_attempt.yml
            path: tasks/kubeconfig-attempt.yml
          - key: tasks_s3_ssl_read_ca.yml
            path: tasks/s3-ssl-read-ca.yml
          - key: tasks_wait_dr_managedclusters_available.yml
            path: tasks/wait-dr-managedclusters-available.yml
      restartPolicy: Never
      serviceAccountName: s3-ssl-sync-sa
  backoffLimit: 10
  activeDeadlineSeconds: 7200
{{- end }}
